### ISSUE TITLE
Pure Bash and Fast

### ISSUE THREAD

**Issue by iam-TJ** [gunitinug/vlsmc#3]
TJ- here. Well, I promised you a pure bash solution in 15 lines. I'm afraid I failed on that - it's 226 lines!

Take a look - and discuss it in #linux next time you're in.

https://iam.tj/projects/misc/vlsmc.tj

**Comment by gunitinug** [comment]
Hi thanks for your post in my github page. 

I've tried `vlsmc.tj -n 10.0.0.0/8 -d LAN1,80 -d LAN2,20 -d LAN3,350 -d LAN4,250 -d LAN5,50 -d WAN1,2 -d WAN2,2 -d WAN3,2 -d WAN4,2 -d WAN5,2 -d WAN6,2` 

Actually this is from Example 3 in https://www.computernetworkingnotes.com/ccna-study-guide/vlsm-subnetting-examples-and-calculation-explained.html 

Your code is very fast but the network addresses of the subnets are wrong.

```
$ ./vlsmc.tj -n 10.0.0.0/8 -d LAN1,80 -d LAN2,20 -d LAN3,350 -d LAN4,250 -d LAN5,50 -d WAN1,2 -d WAN2,2 -d WAN3,2 -d WAN4,2 -d WAN5,2 -d WAN6,2
Net block	: 0.0.10.0/8	: 16777214 hosts
LAN3		: 0.0.10.0/23	: 350 hosts
LAN4		: 0.0.12.0/24	: 250 hosts
LAN1		: 0.0.13.0/25	: 80 hosts
LAN5		: 0.0.13.128/26	: 50 hosts
LAN2		: 0.0.13.192/27	: 20 hosts
WAN1		: 0.0.13.224/30	: 2 hosts
WAN2		: 0.0.13.228/30	: 2 hosts
WAN3		: 0.0.13.232/30	: 2 hosts
WAN4		: 0.0.13.236/30	: 2 hosts
WAN5		: 0.0.13.240/30	: 2 hosts
WAN6		: 0.0.13.244/30	: 2 hosts
```

**Comment by iam-TJ** [comment]
Confirmed - there was a bug in `unsigned2network()` where the value wasn't being shifted left correctly.

**Comment by gunitinug** [comment]
Hey TJ. I rewrote part of my code to use your method. Seems to work. ;)
